modLoader = "javafml"
loaderVersion = "${forge_loader_version_range}"
license = "${license}"
issueTrackerURL = "${issueTrackerURL}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_displayName}"
updateJSONURL = "${updateJSONURL}"
displayURL = "${displayURL}"
logoFile = "${mod_id}.png"
credits = "${credits}"
authors = "${author}"
description = '''${description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[mixins]]
config = "${mod_id}.forge.mixins.json"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_loader_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "forgeconfigapiport"
mandatory = true
versionRange = "${fcap_version_range}"
ordering = "NONE"
side = "BOTH"