modLoader = "javafml"
loaderVersion = "[25,)"
license = "MIT License"
issueTrackerURL = "https://github.com/darkorg69/global-block-hardness/issues"

[[mods]]
modId = "globalblockhardness"
version = "${file.jarVersion}"
displayName = "Global Block Hardness"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/global-block-hardness"
logoFile = "globalblockhardness.png"
credits = "Thanks for this mod goes to Java and the Forge team."
authors = "Darkorg"
description = '''This mod makes breaking blocks harder!'''